[package]
name = "init"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
hearth-guest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
toml = "0.7"
