[workspace]
members = [
  "init",
  "physics",
]
exclude = ["build"]

[workspace.dependencies]
hearth-guest = { git = "https://github.com/hearth-rs/hearth", rev = "050c772" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
