[workspace]
resolver = "2"
members = [
  "init",
  "physics",
  "wm",
]
exclude = ["build"]

[workspace.dependencies]
hearth-guest = { git = "https://github.com/hearth-rs/hearth", rev = "3b5e660" }
serde = { version = "^1.0.103, <1.0.171", features = ["derive"] }
serde_json = "1"
